#!/bin/sh

mkdir -p opk
cp -r ./build/Data opk
cp ./build/CroMagRally opk/CroMagRally
cp ./icon.png opk/icon.png
cp ./start.sh opk/start.sh
cp ./LICENSE.md opk/COPYRIGHT

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=CroMag Rally
Comment=Racing Game
Exec=start.sh
Icon=icon
Terminal=false
Type=Application
X-OD-NeedsJoystick=true
Categories=games;
' > opk/default."$1".desktop

mksquashfs ./opk cromagrally_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
